const throwError = () => {
    throw new Error('We are throwing this error!');
}

export default throwError
